inherit_from: .rubocop_todo.yml

# this is the way the test was written
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/plugin_spec.rb'

# this is the way the test was written
Naming/VariableNumber:
  Exclude:
    - 'spec/plugin_spec.rb'
