#!/usr/bin/env ruby

require 'optimist'
require 'fileutils'
require 'yaml'
require 'json'
require 'pty'
require 'erb'

require 'kaiser'

cli = Kaiser::KaiserCli.new(`pwd`.chomp)

SUB_COMMANDS = %w{[init deinit up down shutdown db_load db_save]}.freeze
Optimist.options do
  banner "Kaiser v#{Kaiser::VERSION}"
  stop_on SUB_COMMANDS
end

cmd = ARGV.shift
cli.send(:"#{cmd}")
