---
name: default
jobs:
  rspec:
    container:
      image: ruby:2.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: setup
      run: |-
        ruby -v
        which ruby
        gem install bundler --no-document
        bundle config path vendor/bundle
        bundle install --jobs 4
    - name: script
      run: bundle exec rspec
  rubocop:
    container:
      image: ruby:2.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: setup
      run: |-
        ruby -v
        which ruby
        gem install bundler --no-document
        bundle config path vendor/bundle
        bundle install --jobs 4
    - name: script
      run: bundle exec rubocop
'on':
  push:
    branches:
    - '*'
