name: docker-branch-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: degicadev
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: setup
      run: |-
        docker build . -t degicadev/kaiser:branch-${{ github.head_ref }}
        docker push degicadev/kaiser:branch-${{ github.head_ref }}

'on':
  push:
    branches:
    - '*'
